config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  devise_for :users
  resources :toppage, only: [:index]
  resources :movies, only: [:index, :show] do
    resources :clips
    resources :reviews, only: [:show, :create] do
      resources :tags, only: [:index, :create]
      resource :comments, only: [:create]
    end
    collection do
      get "search"
      get "clip"
    end
  end
  resource :lists, only: [:index] do
    collection do
      get "now"
      get "comming"
      get "upcomming"
      get "trend"
      get "country"
      get "genre"
      get "year"
      get "tag"
      get "index"
      get "user"
      get "award"
      get "/country/others" => "countries#others"
    end
    resources :countries, only: [:index], path: '/country/:country_id'
    resources :genres, only: [:show]
    resources :years, only: [:index,:show], path: '/year/:age_id'
    resources :tags, only: [:show]
    resources :awards, only: [:show]
  end
  resources :users do
    resources :relationships , only: [:create, :destroy]
    member do
      get "review"
      get "clip"
      get "fan"
      get "followers"
      get "following"
      get "clip"
    end
  end

  resources :members do
    resources :users_members
    collection do
      get "fan"
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :build_review_and_tag_model
  before_action :redirect_to_top

  def now
    @movies = Movie.page(params[:page]).per(36).order("created_at DESC")
    set_movies_infos
  end

  def comming
    @movies = Movie.page(params[:page]).per(36).order("created_at DESC")
    set_movies_infos
  end

  def upcomming
    @movies = Movie.page(params[:page]).per(36).order("created_at DESC")
    set_movies_infos
  end

  def trend
    # reviews = Review.pluck(:movie_id, :score)
    @movies = Movie.page(params[:page]).per(36).order("created_at DESC")
    set_movies_infos
  end

  def country
    @countries = Country.all
  end

  def genre
    @genres = Genre.all
  end

  def year
    @movies_age = Movie.group(:production).order('production DESC').map{|movie| movie.production.to_i}
  end

  def tag
  end

  def award
    @awards = Award.group(:name).order('id ASC').pluck(:name)
  end

  def index
    @movies_now = Movie.order('production DESC').limit(10).order("RAND()").limit(5)
    @movies_comming  = Movie.order('production DESC').limit(5)
    @movies_upcomming  = Movie.order('production DESC').limit(5)
    @movies_trend  = Movie.order("RAND()").limit(5)
    @countries = Country.all
    @genres = Genre.all
    @awards = Award.group(:name)
    @movies_age = Movie.group(:production).order('production DESC').map{|movie| movie.production.to_i}
    @movies_rental = Movie.order('production DESC').limit(10).order("RAND()").limit(3)
  end
  def user
    @users = User.joins(:passive_relationships).group(:followed_id).order('count(follower_id) desc')
  end

  private

  def redirect_to_top
    redirect_to controller: :toppage, action: :index unless user_signed_in?
  end

  def build_review_and_tag_model
    @review = Review.new
    @tag = Tag.new
  end

  def set_movies_infos
    @movies_infos_array = []
    @movies.each do |movie|
      scores_array = []
      movie.reviews.each do |review|
        scores_array << review.score unless review.score == nil
      end
      if scores_array.length > 0
        score_ave = (scores_array.sum) / (scores_array.length)
      end
      movie_infos = {reviews_count: scores_array.length, score_ave: score_ave}
      @movies_infos_array << movie_infos
    end
  end
end

app/views/lists/_lists_content.html.haml
.movie-list-content
  .movie-list-content__tab
    おすすめ順
  .movie-list-content__index.clearfix
    - @movies.each_with_index do |movie, i|
      .list-content
        =link_to movie_path(movie.id) do
          .list-content__image
            = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "150px", height: "200px"
        .list-content__title
          =link_to movie_path(movie.id) do
            %span
              = movie.title
        .list-content__wrapper.clearfix
          =render partial: "reviews/post_form", locals: {movie: movie, review: @review, tag: @tag}
          =link_to "#" do
            .list-content__mark
              =fa_icon "pencil", class: "fa-2x"
              %p.mark__count
                #{movie.reviews.length}
          - if user_signed_in? && movie.clip_user(current_user.id)
            - @clip = movie.clips.find_by(user_id: current_user.id)
            =link_to "#", class: "clip-movie-btn3", "data-clip-id": "#{movie.id}", "data-clip-url": "/movies/#{movie.id}/clips/#{@clip.id}" do
              .list-content__clip
                =fa_icon "paperclip", class: "fa-2x fa-flip-horizontal"
                %p.clip__count
                  #{movie.users.length}
          - else
            =link_to "#", class: "clip-movie-btn4", "data-clip-id": "#{movie.id}", "data-clip-url": "/movies/#{movie.id}/clips" do
              .list-content__clip
                =fa_icon "paperclip", class: "fa-2x fa-flip-horizontal"
                %p.clip__count
                  #{movie.users.length}
          =link_to "#" do
            .list-content__score
              =fa_icon "star",class: "far fa-star"
              %p.score__rate
                -if @movies_infos_array[i][:reviews_count] >= 1
                  %span #{(@movies_infos_array[i][:score_ave]).to_f / 10}
                -else
                  %span -
  .movie-list-content__search
    = paginate(@movies)

app/views/lists/_lists_sidebar.html.haml
.sidebar
  .sidebar__container
    %h2.c-heading-2
      映画を探す
    .sidebar__main
      %nav.c-side-menu
        %ul
          - if params[:action] == "now"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "上映中の映画", now_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "上映中の映画", now_lists_path
          - if params[:action] == "comming"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "公開予定の映画", comming_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "公開予定の映画", comming_lists_path
          - if params[:action] == "upcomming"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "今週公開の映画", upcomming_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "今週公開の映画", upcomming_lists_path
          - if params[:action] == "trend"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "今話題のおすすめ映画", trend_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "今話題のおすすめ映画", trend_lists_path
          - if params[:action] == "year"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "制作年（年代）", year_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "制作年（年代）", year_lists_path
          - if params[:action] == "country"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "制作国", country_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "制作国", country_lists_path
          - if params[:action] == "genre"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "ジャンル", genre_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "ジャンル", genre_lists_path
          - if params[:action] == "tag"
            %li.c-side-menu__items
              %h3.c-side-menu__items_title.active
                = link_to "タグ", tag_lists_path
          - else
            %li.c-side-menu__items
              %h3.c-side-menu__items_title
                = link_to "タグ", tag_lists_path
  .sidebar-banner__contents
    .barnner__content
      = image_tag "banner1.jpeg", alt: "banner_ad"
    .barnner__content
      %iframe{:allow => "autoplay; encrypted-media", :allowfullscreen => "", :frameborder => "0", :height => "250", :src => "https://www.youtube.com/embed/JXJ0ADlG8bg", :width => "300"}

app/views/lists/_search_user_contents.html.haml
.search-user__lists.clearfix
  - @users.each do |user|
    .user__lists-content
      .user__lists-content-info.clearfix
        =link_to href: "" do
          .user__lists-content-thumbnail
            = image_tag "img_people-placehold.svg", alt: "image"
        .user__lists-content-name
          = link_to href:"" do
            %span #{ user.nickname }
          %p #{ user.Filmarks_ID }
      .user__lists-content-follow.clearfix
        .user__lists-content-follow__info
          %p.info-name followers
          %p.info-count{id:"followers-count_userid#{user.id}"} #{ user.followers.count }
        .user__lists-content-follow__info
          %p.info-name followings
          %p.info-count{id:"followings-count_userid#{user.id}"}  #{ user.following.count }
          / ユーザーのログインしているかどうか判断を追記要
        - if user_signed_in?
          - if user != current_user
            .user__lists-content-follow__block
              = link_to href: "" do
                = image_tag "btn_dots.svg", alt: "・・・"
            - if user.followers.find_by(id: current_user.id)
              = link_to user_relationship_path(current_user.id,user.id), method: 'delete' do
                .user__lists-content-follow__btn.follow-btn
            - else
              = link_to user_relationships_path(current_user.id, params:{followed_id: user.id} ), method: 'post' do
                .user__lists-content-follow__btn.unfollow-btn
      .user__lists-content-movies.clearfix
        - clips = user.clips.order("created_at DESC")
        - 3.times do |i|
          - if clips[i]
            =link_to movie_path(clips[i].movie.id) do
              = image_tag "#{ clips[i].movie.image }", width: "89", heigth: "126", class: "movie-image"
          - else
            = image_tag "img_cover-placehold.svg", width: "89", heigth: "126"

app/views/lists/award.html.haml
.search-detail
  .search-detail__wrapper
    .search-detail__header
      .search-detail__header-index.clearfix
        %ul.top-navi
          %li
            = link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            映画賞・映画祭
      .search-detail__header-title
        %p.title__heading 映画賞・映画祭一覧
        %p.title__heading-sub
          アカデミー賞、日本アカデミー賞、ゴールデングローブ賞、東京国際映画祭、世界三大映画祭（カンヌ国際映画祭・ヴェネチア国際映画祭・ベルリン国際映画祭）、サンダンス国際映画祭、トロント国際映画際など、世界各国の映画賞・映画祭の受賞作品を受賞歴や各部門から探せます。
    .search-detail__body
      .search-detail__body-main.clearfix
        .contents-block
          .contents-block__title
            =link_to award_lists_path do
              %span 映画賞
          .contents-block__content
            .contents-block__content-category.clearfix
              %dl.category__award
                - @awards.each do |award|
                  - id = Award.find_by(name: award).id
                  .category__award-list.clearfix
                    %dt
                      = link_to lists_award_path(id:id, name: award ) do
                        %span
                          = "#{ award }"
                      %dd
                        - award_lists = Award.where(name: award)
                        - award_lists.each do |list|
                          = link_to lists_award_path(list.id) do
                            %span
                              = list.subname
      = render partial: "share/barnner_contents"

app/views/lists/comming.html.haml
.movie-list
  .movie-list__wrapper
    .movie-list__header
      .movie-list__header-index.clearfix
        %ul.top-navi
          %li= link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li= link_to "映画作品を探す", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            上映中の最新映画作品
      .movie-list__header-title
        上映中の最新映画
      .movie-list__header-info
        今上映中の最新映画作品おすすめ人気ランキング。公開日、作品情報、上映時間、レビュー・感想・評価をチェックできます。

    .movie-list__body
      .movie-list__body-main.clearfix
        =render partial: "lists_sidebar"
        =render partial: "lists_content"

app/views/lists/country.html.haml
.search-detail
  .search-detail__wrapper
    .search-detail__header
      .search-detail__header-index.clearfix
        %ul.top-navi
          %li
            = link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            映画製作国
      .search-detail__header-title
        %p.title__heading 映画製作国一覧
        %p.title__heading-sub
          製作国別に映画作品を探せます。邦画・洋画だけでなく、中国映画・韓国映画・インド映画などのアジア映画、フランス映画・イタリア映画・ドイツ映画などのヨーロッパ映画や北欧映画まで。
    .search-detail__body
      .search-detail__body-main.clearfix
        .contents-block
          .contents-block__title
            =link_to country_lists_path do
              %span 製作国
          .contents-block__content
            .contents-block__content-category.clearfix
              %ul.countries-lists.clearfix
              - @countries.each do |country|
                .countries-list
                  = link_to lists_countries_path(country.id) do
                    %li.countries-list-name
                      %span
                        = country.name
      = render partial: "share/barnner_contents"

app/views/lists/genre.html.haml
.search-detail
  .search-detail__wrapper
    .search-detail__header
      .search-detail__header-index.clearfix
        %ul.top-navi
          %li
            = link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            映画ジャンル
      .search-detail__header-title
        %p.title__heading 映画製作国一覧
        %p.title__heading-sub
          製作国別に映画作品を探せます。邦画・洋画だけでなく、中国映画・韓国映画・ジャンル別に映画作品を探せます。ドラマ、サスペンス、コメディ、ホラー、SF、恋愛、アニメなどの人気ジャンルから、ドキュメンタリー、時代劇、ミュージカルといったシブめジャンルまで、77445作品から探せます。
    .search-detail__body
      .search-detail__body-main.clearfix
        .contents-block
          .contents-block__title
            =link_to genre_lists_path do
              %span ジャンル
          .contents-block__content
            .contents-block__content-category.clearfix
              %ul.genre-lists
              - @genres.each do |genre|
                = link_to lists_genre_path(genre.id) do
                  %li.genre-list-name
                    %span
                      = genre.name
      = render partial: "share/barnner_contents"

app/views/lists/index.html.haml
.search-detail
  .search-detail__wrapper
    .search-detail__header
      .search-detail__header-index.clearfix
        %ul.top-navi
          %li
            = link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            映画作品を探す
      .search-detail__header-title
        %p.title__heading 映画作品を探す
        %p.title__heading-sub
          上映中映画、公開予定映画、邦画・洋画、製作国別、サスペンス・ドラマ・SFなどのジャンル別、アカデミー賞・カンヌ国際映画祭などの映画賞受賞作品といった様々なテーマで映画を探せます。
    .search-detail__body
      .search-detail__body-main.clearfix
        .contents-block
          .contents-block__title
            =link_to do
              %span 動画配信サービス
          .contents-block__content.clearfix
            =link_to do
              .contents-block__content-link
                =image_tag "logo_ttv.png"
                .link-name
                  %span TUTAYA TV
            =link_to do
              .contents-block__content-link
                =image_tag "video-market.png"
                .link-name
                  %span ビデオマーケット
            =link_to do
              .contents-block__content-link
                =image_tag "logo_unext.png"
                .link-name
                  %span U-NEXT
            =link_to do
              .contents-block__content-link
                =image_tag "videopass_logo.png"
                .link-name
                  %span ビデオパス
            =link_to do
              .contents-block__content-link
                =image_tag "hulu_logo.png"
                .link-name
                  %span Hulu
            =link_to do
              .contents-block__content-link
                =image_tag "logo_netflix_logo.png"
                .link-name
                  %span netflix
        .contents-block.clearfix
          .contents-block__recommended
            .contents-block__recommended-showing
              .contents-block__title
                =link_to now_lists_path do
                  %span 上映中
              .contents-block__image.clearfix
                - @movies_now.each do |movie|
                  =link_to movie_path(movie.id) do
                    .contents-block__image__list
                      = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "90px", height: "120px"
              .contents-block__link
                .contents-block__link-btn
                  =link_to "もっと見る　>", now_lists_path
            .contents-block__recommended-showing
              .contents-block__title
                =link_to comming_lists_path do
                  %span 公開予定の映画
              .contents-block__image.clearfix
                - @movies_comming.each do |movie|
                  =link_to movie_path(movie.id) do
                    .contents-block__image__list
                      = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "90px", height: "120px"
              .contents-block__link
                .contents-block__link-btn
                  =link_to "もっと見る　>", comming_lists_path
            .contents-block__recommended-showing
              .contents-block__title
                =link_to upcomming_lists_path do
                  %span 今週公開の映画
              .contents-block__image.clearfix
                - @movies_upcomming.each do |movie|
                  =link_to movie_path(movie.id) do
                    .contents-block__image__list
                      = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "90px", height: "120px"
              .contents-block__link
                .contents-block__link-btn
                  =link_to "もっと見る　>", upcomming_lists_path
            .contents-block__recommended-showing
              .contents-block__title
                =link_to trend_lists_path do
                  %span 今話題のおすすめ映画
              .contents-block__image.clearfix
                - @movies_trend.each do |movie|
                  =link_to movie_path(movie.id) do
                    .contents-block__image__list
                      = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "90px", height: "120px"
              .contents-block__link
                .contents-block__link-btn
                  =link_to "もっと見る　>", trend_lists_path
        .contents-block
          .contents-block__title
            =link_to country_lists_path do
              %span 製作国
          .contents-block__content
            .contents-block__content-category.clearfix
              %ul.countries-lists.clearfix
              - i = 1
              - @countries.each do |country|
                - if i <= 15
                  .countries-list
                    = link_to lists_countries_path(country.id) do
                      %li.countries-list-name
                        %span
                          = country.name
                - else
                  .countries-list.hidden
                    = link_to lists_countries_path(country.id) do
                      %li.countries-list-name
                        %span
                          = country.name
                - i = i + 1
              - if i > 10
                .category-list__hidden.readmore.arrow-down
                  もっと見る
        .contents-block
          .contents-block__title
            =link_to genre_lists_path do
              %span ジャンル
          .contents-block__content
            .contents-block__content-category.clearfix
              %ul.genre-lists
              - @genres.each do |genre|
                = link_to lists_genre_path(genre.id) do
                  %li.genre-list-name
                    %span
                      = genre.name
        .contents-block
          .contents-block__title
            =link_to award_lists_path do
              %span 映画賞
          .contents-block__content
            .contents-block__content-category.clearfix
              %ul.award-lists
              -i = 1
              - @awards.each do |award|
                - if i <= 9
                  .award-list
                    = link_to lists_award_path(award.id, name: award.name) do
                      %li.award-list-name
                        %span
                          = award.name
                - else
                  .award-list.hidden
                    = link_to lists_award_path(award.id) do
                      %li.award-list-name
                        %span
                          = award.name
                - i = i +1
              - if i > 10
                .category-list__hidden.readmore.arrow-down
                  もっと見る
        .contents-block
          .contents-block__title
            =link_to year_lists_path do
              %span 製作年
          .contents-block__content
            .contents-block__content-category.clearfix
              %dl.category__year
                - age_first = (@movies_age.first/10.to_f).floor*10
                - age_last = (@movies_age.last/10.to_f).floor*10
                - list_count = 1
                - age_first.step age_last,-10 do |num|
                  - movies = Movie.where("production >= ?", num).where("production < ?", num + 10).group(:production)
                  - if movies.length != 0
                    - if list_count <= 3
                      .category__year-list.clearfix
                        %dt
                          = link_to lists_years_path("#{ num }s") do
                            %span
                              = "#{ num }年代"
                        %dd
                          - movies.each do |movie|
                            = link_to lists_year_path("#{ num }s", movie.production.to_i) do
                              %span
                                = "#{ movie.production }"
                    - else
                      .category__year-list.hidden.clearfix
                        %dt
                          = link_to lists_years_path("#{ num }s") do
                            %span
                              = "#{ num }年代"
                        %dd
                          - movies.each do |movie|
                            = link_to lists_year_path("#{ num }s", movie.production.to_i) do
                              %span
                                = "#{ movie.production }"
                    - list_count = list_count + 1
                - if list_count > 4
                  .category-list__hidden.readmore.arrow-down
                    もっと見る
        .contents-block-sub
          .contents-block__title
            =link_to do
              %span 新作レンタル
          .contents-block__content
            .contents-block__content-category.clearfix
              - @movies_rental.each do |movie|
                =link_to movie_path(movie.id) do
                  .contents-block__image__list
                    = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "90px", height: "120px"
          .contents-block-sub__link
            .contents-block-sub__link-btn
              =link_to "もっと見る　>"
        .contents-block-sub.margin
          .contents-block__title
            =link_to do
              %span レンタル予定の映画
          .contents-block__content
            .contents-block__content-category.clearfix
              - @movies_rental.each do |movie|
                =link_to movie_path(movie.id) do
                  .contents-block__image__list
                    = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "90px", height: "120px"
          .contents-block-sub__link
            .contents-block-sub__link-btn
              =link_to "もっと見る　>"
        .contents-block-sub.margin
          .contents-block__title
            =link_to do
              %span #タグ
          .contents-block__content
            .contents-block__content-category
              = link_to  do
                .tag-list
                  %span
                    = '#映画'
              = link_to  do
                .tag-list
                  %span
                    = '#記録'
              = link_to  do
                .tag-list
                  %span
                    = '#DVD'
          .contents-block-sub__link
            .contents-block-sub__link-btn
              =link_to "もっと見る　>"
      = render partial: "share/barnner_contents"

app/views/lists/now.html.haml
.movie-list
  .movie-list__wrapper
    .movie-list__header
      .movie-list__header-index.clearfix
        %ul.top-navi
          %li= link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li= link_to "映画作品を探す", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            今週公開の映画作品
      .movie-list__header-title
        今週公開の映画
      .movie-list__header-info
        今週末に公開・上映開始される新作映画作品。

    .movie-list__body
      .movie-list__body-main.clearfix
        =render partial: "lists_sidebar"
        =render partial: "lists_content"

app/views/lists/upcomming.html.haml
.movie-list
  .movie-list__wrapper
    .movie-list__header
      .movie-list__header-index.clearfix
        %ul.top-navi
          %li= link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li= link_to "映画作品を探す", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            公開予定の映画作品
      .movie-list__header-title
        公開予定の映画
      .movie-list__header-info
        近日公開予定・上映予定の最新映画作品。2018年2月公開予定映画の作品情報、あらすじ、感想・評価・レビューをチェック。

    .movie-list__body
      .movie-list__body-main.clearfix
        =render partial: "lists_sidebar"
        =render partial: "lists_content"

app/views/lists/user.html.haml
.search-detail
  .search-detail__wrapper
    .search-detail__header
      .search-detail__header-index.clearfix
        %ul.top-navi
          %li= link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            ユーザーを探す
      .search-detail__header-title
        人気ユーザー #{ @users.length }人
    .search-detail__body
      .search-detail__body-main.clearfix
        .sidebar
          .sidebar__container
            %h2.c-heading-2
              ユーザーを探す
            .sidebar__main
              %nav.c-side-menu
                %ul
                  %li.c-side-menu__items
                    %h3.c-side-menu__items_title.active
                      = link_to "人気ユーザー", search_movies_path(keyword: "#{params[:keyword]}",button: "movie")
                  %li.c-side-menu__items
                    %h3.c-side-menu__items_title
                      = link_to "Facebookから探す"
                  %li.c-side-menu__items
                    %h3.c-side-menu__items_title
                      = link_to "Twitterから探す"
          .sidebar-banner__contents
            .barnner__content
              = image_tag "banner1.jpeg", alt: "banner_ad"
            .barnner__content
              %iframe{:allow => "autoplay; encrypted-media", :allowfullscreen => "", :frameborder => "0", :height => "250", :src => "https://www.youtube.com/embed/JXJ0ADlG8bg", :width => "300"}
        = render partial: "lists/search_user_contents"
      = render partial: "share/barnner_contents"

app/views/lists/year.html.haml
.search-detail
  .search-detail__wrapper
    .search-detail__header
      .search-detail__header-index.clearfix
        %ul.top-navi
          %li
            = link_to "Filmarks映画情報", root_path
          %li
            &nbsp;>&nbsp;&nbsp;
          %li
            映画製作年代・製作年
      .search-detail__header-title
        %p.title__heading 映画製作年代・製作年一覧
        %p.title__heading-sub
          製作年代や製作年から時代ごとの映画作品を探すことが出来ます。懐かしい映画から2018年公開の最新の映画まで
    .search-detail__body
      .search-detail__body-main.clearfix
        .contents-block
          .contents-block__title
            =link_to year_lists_path do
              %span 制作年
          .contents-block__content
            .contents-block__content-category.clearfix
              %dl.category__year
                - age_first = (@movies_age.first/10.to_f).floor*10
                - age_last = (@movies_age.last/10.to_f).floor*10
                - age_first.step age_last,-10 do |num|
                  - movies = Movie.where("production >= ?", num).where("production < ?", num + 10).group(:production)
                  - if movies.length != 0
                    .category__year-list.clearfix
                      %dt
                        = link_to lists_years_path("#{ num }s") do
                          %span
                            = "#{ num }年代"
                      %dd
                        - movies.each do |movie|
                          = link_to lists_year_path("#{ num }s", movie.production.to_i) do
                            %span
                              = "#{ movie.production }"
      = render partial: "share/barnner_contents"