config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  devise_for :users
  resources :toppage, only: [:index]
  resources :movies, only: [:index, :show] do
    resources :clips
    resources :reviews, only: [:show, :create] do
      resources :tags, only: [:index, :create]
      resource :comments, only: [:create]
    end
    collection do
      get "search"
      get "clip"
    end
  end
  resource :lists, only: [:index] do
    collection do
      get "now"
      get "comming"
      get "upcomming"
      get "trend"
      get "country"
      get "genre"
      get "year"
      get "tag"
      get "index"
      get "user"
      get "award"
      get "/country/others" => "countries#others"
    end
    resources :countries, only: [:index], path: '/country/:country_id'
    resources :genres, only: [:show]
    resources :years, only: [:index,:show], path: '/year/:age_id'
    resources :tags, only: [:show]
    resources :awards, only: [:show]
  end
  resources :users do
    resources :relationships , only: [:create, :destroy]
    member do
      get "review"
      get "clip"
      get "fan"
      get "followers"
      get "following"
      get "clip"
    end
  end

  resources :members do
    resources :users_members
    collection do
      get "fan"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :Filmarks_ID, length: { in: 1..15 }
  validates :nickname, presence: true
  # validates_acceptance_of :checkbox, allow_nil: false, on: :create

  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :movies, through: :clips
  has_many :clips, dependent: :destroy
  has_many :members, through: :users_members
  has_many :users_members
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :build_review_and_tag_model
  before_action :redirect_to_top

  def review
    if user_signed_in?
      user = current_user
      @user_actions = user.reviews.order('created_at DESC').page(params[:page]).per(10)
      @comment = Comment.new
    else
      redirect_to controller: :toppage, action: :index
    end
  end

  def clip
    @movies = current_user.movies.page(params[:page]).per(36)
    set_movies_infos
  end

  def followers
    @followers = current_user.followers.page(params[:page]).per(36)
  end

  def following
    @following = current_user.following.page(params[:page]).per(36)
  end

  def fan
    @casts = current_user.members.page(params[:page]).per(36)
  end


  private
  def redirect_to_top
    redirect_to controller: :toppage, action: :index unless user_signed_in?
  end

  def build_review_and_tag_model
    @review = Review.new
    @tag = Tag.new
  end

  def set_movies_infos
    @movies_infos_array = []
    @movies.each do |movie|
      scores_array = []
      movie.reviews.each do |review|
        scores_array << review.score unless review.score == nil
      end
      if scores_array.length > 0
        score_ave = (scores_array.sum) / (scores_array.length)
      end
      movie_infos = {reviews_count: scores_array.length, score_ave: score_ave}
      @movies_infos_array << movie_infos
    end
  end
end

app/views/users/_header.html.haml
.my-profile__wrapper
  .aaa
    .top-navi
      %ul
        %li
          =link_to "Filmarks映画情報", root_path
        %li
          >
        %li
          #{current_user.nickname}さんの鑑賞した映画
    .my-profile
      .my-profile__img
        =image_tag "img_people-placehold"
      .my-profile__name
        .my-profile__name__nick
          #{current_user.nickname}
        .my-profile__name__id
          @#{current_user.Filmarks_ID}
      .my-profile__edit
        =link_to "プロフィールを編集する"
.users-navi__wrapper
  .iii
    %ul.users-navi

      -if params[:action] == "review"
        %li.users-navi__review.yellow-bg
          =link_to review_user_path do
            =fa_icon "pencil"
            %p #{current_user.reviews.length}
      -else
        %li.users-navi__review
          =link_to review_user_path do
            =fa_icon "pencil"
            %p #{current_user.reviews.length}
      -if params[:action] == "clip"
        %li.users-navi__clip.yellow-bg
          =link_to clip_user_path do
            =fa_icon "paperclip", class: "fa-flip-horizontal"
            %p #{current_user.clips.length}
      -else
        %li.users-navi__clip
          =link_to clip_user_path do
            =fa_icon "paperclip", class: "fa-flip-horizontal"
            %p #{current_user.clips.length}
      -if params[:action] == "fan"
        %li.users-navi__fan.yellow-bg
          =link_to fan_user_path do
            =fa_icon "user-plus"
            %p 0
      -else
        %li.users-navi__fan
          =link_to fan_user_path do
            =fa_icon "user-plus"
            %p 0
      -if params[:action] == "followers"
        %li.users-navi__followers.yellow-bg
          =link_to followers_user_path do
            %p Followers
            %p #{current_user.followers.length}
      -else
        %li.users-navi__followers
          =link_to followers_user_path do
            %p Followers
            %p #{current_user.followers.length}
      -if params[:action] == "following"
        %li.users-navi__following.yellow-bg
          =link_to following_user_path do
            %p Following
            %p #{current_user.following.length}
      -else
        %li.users-navi__following
          =link_to following_user_path do
            %p Following
            %p #{current_user.following.length}

app/views/users/clip.html.haml
.my-page
  .my-page__header
    =render partial: "header"
  .my-page__reviews.clearfix
    .movie-list-content__index.clearfix
      - @movies.each_with_index do |movie, i|
        .list-content
          =link_to movie_path(movie.id) do
            .list-content__image
              = image_tag "#{ movie.image }", alt: "#{ movie.title }", width: "140px", height: "200px"
          .list-content__title
            =link_to movie_path(movie.id) do
              %span
                = movie.title
          .list-content__wrapper.clearfix
            =render partial: "reviews/post_form", locals: {movie: movie, review: @review, tag: @tag}
            =link_to "#" do
              .list-content__mark
                =fa_icon "pencil", class: "fa-2x"
                %p.mark__count
                  #{movie.reviews.length}
            - if user_signed_in? && movie.clip_user(current_user.id)
              - @clip = movie.clips.find_by(user_id: current_user.id)
              =link_to "#", class: "clip-movie-btn3", "data-clip-id": "#{movie.id}", "data-clip-url": "/movies/#{movie.id}/clips/#{@clip.id}" do
                .list-content__clip
                  =fa_icon "paperclip", class: "fa-2x fa-flip-horizontal"
                  %p.clip__count
                    #{movie.users.length}
            - else
              =link_to "#", class: "clip-movie-btn4", "data-clip-id": "#{movie.id}", "data-clip-url": "/movies/#{movie.id}/clips" do
                .list-content__clip
                  =fa_icon "paperclip", class: "fa-2x fa-flip-horizontal"
                  %p.clip__count
                    #{movie.users.length}
            =link_to "#" do
              .list-content__score
                =fa_icon "star",class: "far fa-star"
                %p.score__rate
                  -if @movies_infos_array[i][:reviews_count] >= 1
                    %span #{(@movies_infos_array[i][:score_ave]).to_f / 10}
                  -else
                    %span -
    .movie-list-content__search
      = paginate(@movies)

app/views/users/fan.html.haml
.my-page
  .my-page__header
    =render partial: "header"
  .my-page__reviews.clearfix
    .search-cast__lists.clearfix
      - @casts.each do |cast|
        .cast__lists-content
          =link_to href: "" do
            .cast__lists-content-thumbnail
              = image_tag "img_people-placehold.svg", alt: "image"
          .cast__lists-content-name
            = link_to href:"" do
              %span #{ cast.name }
            %p 出身地:
          .cast__lists-content-fun.clearfix
            .cast__lists-content-fun__count
              %span
                Fanが
                %strong  #{ cast.users.length }
                人います
            - if cast.fan_user(current_user.id)
              = button_tag  type: "submit", class: "fun__btn1", "data-fan-id": "#{cast.id}", "data-fan-url": "/members/#{cast.id}/users_members/#{cast.users_members.find_by(user_id: current_user.id).id}" do
                = image_tag "btn_fan.svg", alt: "fun_btn-image"
            - else
              = button_tag  type: "submit", class: "fun__btn2", "data-fan-id": "#{cast.id}", "data-fan-url": "/members/#{cast.id}/users_members" do
                = image_tag "btn_fan.svg", alt: "fun_btn-image"
          .cast__lists-content-movie
            - movies = MoviesMember.where(member_id:cast.id).group('movie_id').map(&:movie)
            - 3.times do |i|
              - if movies[i]
                =link_to  movie_path(movies[i].id) do
                  = image_tag "#{ movies[i].image }", width: "89", heigth: "126", class: "movie-image"
              - else
                = image_tag "img_cover-placehold.svg", width: "89", heigth: "126"
    .movie-list-content__search
      = paginate(@casts)

app/views/users/followers.html.haml
.my-page
  .my-page__header
    =render partial: "header"
  .my-page__reviews.clearfix
    .search-user__lists.clearfix
      - @followers.each do |user|
        .user__lists-content
          .user__lists-content-info.clearfix
            =link_to href: "" do
              .user__lists-content-thumbnail
                = image_tag "img_people-placehold.svg", alt: "image"
            .user__lists-content-name
              = link_to href:"" do
                %span #{ user.nickname }
              %p #{ user.Filmarks_ID }
          .user__lists-content-follow.clearfix
            .user__lists-content-follow__info
              %p.info-name followers
              %p.info-count{id:"followers-count_userid#{user.id}"} #{ user.followers.count }
            .user__lists-content-follow__info
              %p.info-name followings
              %p.info-count{id:"followings-count_userid#{user.id}"}  #{ user.following.count }
              / ユーザーのログインしているかどうか判断を追記要
            - if user_signed_in?
              - if user != current_user
                .user__lists-content-follow__block
                  = link_to href: "" do
                    = image_tag "btn_dots.svg", alt: "・・・"
                - if user.followers.find_by(id: current_user.id)
                  = link_to user_relationship_path(current_user.id,user.id), method: 'delete' do
                    .user__lists-content-follow__btn.follow-btn
                - else
                  = link_to user_relationships_path(current_user.id, params:{followed_id: user.id} ), method: 'post' do
                    .user__lists-content-follow__btn.unfollow-btn
          .user__lists-content-movies.clearfix
            - clips = user.clips.order("created_at DESC")
            - 3.times do |i|
              - if clips[i]
                =link_to movie_path(clips[i].movie.id) do
                  = image_tag "#{ clips[i].movie.image }", width: "89", heigth: "126", class: "movie-image"
              - else
                = image_tag "img_cover-placehold.svg", width: "89", heigth: "126"
    .movie-list-content__search
      = paginate(@followers)

app/views/users/following.html.haml
.my-page
  .my-page__header
    =render partial: "header"
  .my-page__reviews.clearfix
    .search-user__lists.clearfix
      - @following.each do |user|
        .user__lists-content
          .user__lists-content-info.clearfix
            =link_to href: "" do
              .user__lists-content-thumbnail
                = image_tag "img_people-placehold.svg", alt: "image"
            .user__lists-content-name
              = link_to href:"" do
                %span #{ user.nickname }
              %p #{ user.Filmarks_ID }
          .user__lists-content-follow.clearfix
            .user__lists-content-follow__info
              %p.info-name followers
              %p.info-count{id:"followers-count_userid#{user.id}"} #{ user.followers.count }
            .user__lists-content-follow__info
              %p.info-name followings
              %p.info-count{id:"followings-count_userid#{user.id}"}  #{ user.following.count }
              / ユーザーのログインしているかどうか判断を追記要
            - if user_signed_in?
              - if user != current_user
                .user__lists-content-follow__block
                  = link_to href: "" do
                    = image_tag "btn_dots.svg", alt: "・・・"
                - if user.followers.find_by(id: current_user.id)
                  = link_to user_relationship_path(current_user.id,user.id), method: 'delete' do
                    .user__lists-content-follow__btn.follow-btn
                - else
                  = link_to user_relationships_path(current_user.id, params:{followed_id: user.id} ), method: 'post' do
                    .user__lists-content-follow__btn.unfollow-btn
          .user__lists-content-movies.clearfix
            - clips = user.clips.order("created_at DESC")
            - 3.times do |i|
              - if clips[i]
                =link_to movie_path(clips[i].movie.id) do
                  = image_tag "#{ clips[i].movie.image }", width: "89", heigth: "126", class: "movie-image"
              - else
                = image_tag "img_cover-placehold.svg", width: "89", heigth: "126"
    .movie-list-content__search
      = paginate(@following)

app/views/users/fun.html.haml
.my-page
  .my-page__header
    =render partial: "header"
  .my-page__reviews.clearfix
    .search-cast__lists.clearfix
      - @casts.each do |cast|
        .cast__lists-content
          =link_to href: "" do
            .cast__lists-content-thumbnail
              = image_tag "img_people-placehold.svg", alt: "image"
          .cast__lists-content-name
            = link_to href:"" do
              %span #{ cast.name }
            %p 出身地:
          .cast__lists-content-fun.clearfix
            .cast__lists-content-fun__count
              %span
                Fanが
                %strong  #{ cast.users.length }
                人います
            - if cast.fan_user(current_user.id)
              = button_tag  type: "submit", class: "fun__btn1", "data-fan-id": "#{cast.id}", "data-fan-url": "/members/#{cast.id}/users_members/#{cast.users_members.find_by(user_id: current_user.id).id}" do
                = image_tag "btn_fan.svg", alt: "fun_btn-image"
            - else
              = button_tag  type: "submit", class: "fun__btn2", "data-fan-id": "#{cast.id}", "data-fan-url": "/members/#{cast.id}/users_members" do
                = image_tag "btn_fan.svg", alt: "fun_btn-image"
          .cast__lists-content-movie
            - movies = MoviesMember.where(member_id:cast.id).group('movie_id').map(&:movie)
            - 3.times do |i|
              - if movies[i]
                =link_to  movie_path(movies[i].id) do
                  = image_tag "#{ movies[i].image }", width: "89", heigth: "126", class: "movie-image"
              - else
                = image_tag "img_cover-placehold.svg", width: "89", heigth: "126"
    .movie-list-content__search
      = paginate(@casts)

app/views/users/review.html.haml
.my-page
  .my-page__header
    =render partial: "header"
  .my-page__reviews.clearfix
    - @user_actions.each do |user_action|
      .timeline__main-content
        .timeline__main-content__wrapper.clearfix
          .timeline__main-content-left
            .user-info.clearfix
              .user-info__lists-content-thumbnail
                = image_tag "img_people-placehold.svg", alt: "image"
              .user-info__lists-content-info
                = link_to user_path(user_action.user.id) do
                  %p.user_name
                    = "#{ user_action.user.nickname }の感想・レビュー"
                %p.action_time
                  = "#{user_action.created_at.strftime("%Y年%m月%d日 %H時%M分")}"
            .movie-info
              =link_to "#{user_action.movie.title}", movie_path(user_action.movie.id)
              %span
                = "(#{user_action.movie.production}製作映画)"
              -if user_action.score == nil
                .user-review-rate{"data-review-rate": "0"}
                  %span{class: "user-rate user-rate-0"}
                  %spna{class: "user-review-rate-ave"} -
              -else
                .user-review-rate{"data-review-rate": "#{user_action.score}"}
                  %span{class: "user-rate user-rate-#{user_action.score}"}
                  %spna{class: "user-review-rate-ave"} #{(user_action.score).to_f / 10}
            .review-info
              .review-info__comment
                #{user_action.comment}
              .review-info__tags
                %ul
                  - user_action.tags.each do |tag|
                    %li
                      =link_to "#{tag.name}"
          .timeline__main-content-right
            .list-content
              =link_to movie_path(user_action.movie.id) do
                .list-content__image
                  = image_tag "#{ user_action.movie.image }", alt: "#{ user_action.movie.title }", width: "150px", height: "200px"
              .list-content__wrapper.clearfix
                =render partial: "reviews/post_form", locals: {movie: user_action.movie, review: @review, tag: @tag}
                =link_to "#" do
                  .list-content__mark
                    =fa_icon "pencil", class: "fa-2x"
                    %p.mark__count
                      #{user_action.movie.reviews.length}
                - if user_action.movie.clip_user(current_user.id)
                  - @clip = user_action.movie.clips.find_by(user_id: current_user.id)
                  =link_to "#", class: "clip-movie-btn3", "data-clip-id": "#{user_action.movie.id}", "data-clip-url": "/movies/#{user_action.movie.id}/clips/#{@clip.id}" do
                    .list-content__clip
                      =fa_icon "paperclip", class: "fa-2x fa-flip-horizontal"
                      %p.clip__count
                        #{user_action.movie.users.length}
                - else
                  =link_to "#", class: "clip-movie-btn4", "data-clip-id": "#{user_action.movie.id}", "data-clip-url": "/movies/#{user_action.movie.id}/clips" do
                    .list-content__clip
                      =fa_icon "paperclip", class: "fa-2x fa-flip-horizontal"
                      %p.clip__count
                        #{user_action.movie.users.length}
        .timeline__main-content__reactions.clearfix
          .reactions__button.reactions__button--likes
            =link_to do
              =fa_icon "heart"
              %p いいね！
            %span 0
          .reactions__button.reactions__button--comment
            =link_to movie_review_path(user_action.movie.id, user_action.id) do
              =fa_icon "comment"
              %p コメント
            %span #{user_action.comments.length}
    .movie-list-content__search
      = paginate(@user_actions)

app/views/users/review_kido.html.haml
- current_user.reviews.each do |review|
  .mark-card
  .mark-card__header.clearfix
    .user-image
      =link_to do
        =image_tag("img_people-placehold", size: "50x50")
    .review-infos
      =link_to "#{review.user.nickname}の感想・評価"
      %time.review-date{datetime: "#{review.created_at}"} #{review.created_at}
      -if review.score == nil
        .user-review-rate{"data-review-rate": "0"}
          %span{class: "user-rate user-rate-0"}
          %spna{class: "user-review-rate-ave"} -
      -else
        .user-review-rate{"data-review-rate": "#{review.score}"}
          %span{class: "user-rate user-rate-#{review.score}"}
          %spna{class: "user-review-rate-ave"} #{(review.score).to_f / 10}
  .mark-card__body
    #{review.comment}
  .mark-card__tags
    %ul
      -review.tags.each do |tag|
        %li
          =link_to "#{tag.name}"
  .mark-card__reactions
    .reactions__button.reactions__button--likes
      =link_to do
        =fa_icon "heart"
        %p いいね！
      %span 0
    .reactions__button.reactions__button--comment
      =link_to movie_review_path(review.movie.id, review.id) do
        =fa_icon "comment"
        %p コメントする
      %span 0

app/views/users/show.html.haml
= link_to "review(#{current_user.reviews.length})", review_user_path
= link_to "clip(#{current_user.clips.length})", clip_user_path
= link_to "fan(#{current_user.members.length})", fun_user_path
= link_to "follower(#{current_user.followers.length})", followers_user_path
= link_to "following(#{current_user.following.length})", following_user_path